spring.application.name=demo

#Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/astock
spring.datasource.username=SEU_USUARIO
spring.datasource.password=SUA_SENHA

#JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true